### ISSUE TITLE
Error executing 

### ISSUE THREAD

**Issue by B16f00t** [Smart-Space/tkwebview2#7] opened 2023-01-18 18:40 UTC
File "C:\Users\-----\PycharmProjects\pythonProject1\venv\lib\site-packages\tkwebview2\tkwebview2.py", line 22, in __init__
    window=Window(uid,str(id(self)), url=None, html=None, js_api=None, width=width, height=height, x=None, y=None,
TypeError: __init__() missing 3 required positional arguments: 'zoomable', 'draggable', and 'vibrancy

**Comment by Smart-Space** [comment] 2023-01-19 03:58
感谢反馈。
这个问题是由于pywebview在新版本（4.0）中增加了网页浏览控件的新属性导致的，现在已经对其进行修复。

Thanks for the feedback.
This problem is caused by the new arguments added in pywebview's new version 4.0. It has got fixed now.

**Closed as completed by Smart-Space** 2023-01-19 03:58 UTC
